//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.AllBookingDetails = new HashSet<BookingDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public int ID_Company { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<BookingDetail> AllBookingDetails { get; set; }
    }
}
