//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.AllBookingDetails = new HashSet<BookingDetail>();
        }
    
        public int ID { get; set; }
        public int ID_Company { get; set; }
        public int ID_Room { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<BookingDetail> AllBookingDetails { get; set; }
        public virtual Company Company { get; set; }
        public virtual Room Room { get; set; }
    }
}
