//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public BookingDetail()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int ID { get; set; }
        public int ID_Booking { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
