//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.AllBills = new HashSet<Bill>();
            this.AllBookings = new HashSet<Booking>();
            this.AllUsers = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<Bill> AllBills { get; set; }
        public virtual ICollection<Booking> AllBookings { get; set; }
        public virtual ICollection<User> AllUsers { get; set; }
    }
}
