//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.AllRoomFacilities = new HashSet<RoomFacility>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<RoomFacility> AllRoomFacilities { get; set; }
    }
}
