//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class innovation4austriaEntities : DbContext
    {
        public innovation4austriaEntities()
            : base("name=innovation4austriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill> AllBills { get; set; }
        public DbSet<BookingDetail> AllBookingDetails { get; set; }
        public DbSet<Booking> AllBookings { get; set; }
        public DbSet<Building> AllBuildings { get; set; }
        public DbSet<Company> AllCompanies { get; set; }
        public DbSet<Facility> AllFacilities { get; set; }
        public DbSet<LogEntry> AllLogEntries { get; set; }
        public DbSet<Role> AllRoles { get; set; }
        public DbSet<RoomFacility> AllRoomFacilities { get; set; }
        public DbSet<Room> AllRooms { get; set; }
        public DbSet<User> AllUsers { get; set; }
        public DbSet<Type> AllTypes { get; set; }
    }
}
