//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.AllBookings = new HashSet<Booking>();
            this.AllRoomFacilities = new HashSet<RoomFacility>();
        }
    
        public int ID { get; set; }
        public int ID_Building { get; set; }
        public decimal Size { get; set; }
        public decimal PricePerDay { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Booking> AllBookings { get; set; }
        public virtual Building Building { get; set; }
        public virtual ICollection<RoomFacility> AllRoomFacilities { get; set; }
    }
}
