//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFacility
    {
        public int ID_Room { get; set; }
        public int ID_Facility { get; set; }
        public int Quantity { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Room Room { get; set; }
    }
}
