//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AllLogEntries = new HashSet<LogEntry>();
        }
    
        public int ID { get; set; }
        public int ID_Role { get; set; }
        public int ID_Company { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Active { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<LogEntry> AllLogEntries { get; set; }
        public virtual Role Role { get; set; }
    }
}
